version: '3.8'

services:
  node:
    container_name: react-mastermind
    restart: always
    build: .
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: mongodb://mongo/Highscores?retryWrites=true&w=majority

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
