apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-mastermind-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: react-mastermind
        image: vrobl001/react-mastermind:test2
        resources:
        ports:
          - containerPort: 3000
        env:
        - name: HOST
          value: 127.0.0.1
        - name: DANGEROUSLY_DISABLE_HOST_CHECK
          value: "true"
        #   - name: MONGO_HOST
        #     value: mongo-service
        #   - name: MONGO_PORT
        #     value: "27017"
