apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-mastermind-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: react-mastermind
        image: vrobl001/react-mastermind:dev
        resources:
        ports:
          - containerPort: 3000
        env:
        - name: DANGEROUSLY_DISABLE_HOST_CHECK
          value: "true"
        - name: DATABASE_URL
          value: mongodb://mongo-service/Highscores?retryWrites=true&w=majority
