apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-mastermind-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: react-mastermind
        image: vrobl001/react-mastermind
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
